#!/usr/bin/env bash

cd "$(dirname "${0}")" || exit 1

lxqt-panel &
sleep 1

# start services
goreman -f Procfile start & 

# set wallpaper
swaybg -i "$HOME"/.local/share/backgrounds/default.png -m fit &
