#!/usr/bin/env bash

systemctl --user start desktop-session.target
dbus-update-activation-environment --all

cd "$(dirname "${0}")" || exit 1

lxqt-panel &
swaybg -i "$HOME"/.local/share/backgrounds/default.png -m fit &

sleep 2

goreman -f Procfile start &
