#!/usr/bin/env bash

systemctl --user start desktop-session.target

wlr-randr --output DP-1 --mode 2560x1440@199.992004

cd "$(dirname "${0}")" || exit 1

lxqt-panel &
swaybg -i "$HOME"/.local/share/backgrounds/default.png -m fit &

sleep 2

goreman -f Procfile start &
